const carsData = [
  {
    id: 1,
    name: "Tata Nexon",
    brand: "Tata",
    price: 950000,
    year: 2023,
    mileage: "17 km/l",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1199 cc",
    rating: 4.5,
    image: "images/cars/tata-nexon.jpg",
    description: "A compact SUV with strong safety ratings, punchy performance, and practical cabin space for city and highway use."
  },
  {
    id: 2,
    name: "Tata Nexon EV",
    brand: "Tata",
    price: 1650000,
    year: 2024,
    mileage: "453 km/charge",
    fuel: "Electric",
    transmission: "Automatic",
    engine: "Permanent Magnet Synchronous Motor",
    rating: 4.6,
    image: "images/cars/tata-nexon-ev.jpg",
    description: "An all-electric version of the Nexon offering brisk acceleration, low running costs, and practical real-world range."
  },
  {
    id: 3,
    name: "Tata Harrier",
    brand: "Tata",
    price: 2100000,
    year: 2022,
    mileage: "16 km/l",
    fuel: "Diesel",
    transmission: "Manual",
    engine: "1956 cc",
    rating: 4.4,
    image: "images/cars/tata-harrier.jpg",
    description: "A bold-looking mid-size SUV with a spacious cabin, strong diesel engine, and commanding road presence."
  },
  {
    id: 4,
    name: "Tata Altroz",
    brand: "Tata",
    price: 800000,
    year: 2021,
    mileage: "19 km/l",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1199 cc",
    rating: 4.2,
    image: "images/cars/tata-altroz.jpg",
    description: "A premium hatchback known for its 5-star safety rating, solid build quality, and comfortable ride."
  },
  {
    id: 5,
    name: "Hyundai Creta",
    brand: "Hyundai",
    price: 1450000,
    year: 2023,
    mileage: "17 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1497 cc",
    rating: 4.7,
    image: "images/cars/hyundai-creta.jpg",
    description: "A hugely popular compact SUV offering a feature-rich cabin, refined engine options, and a comfortable ride."
  },
  {
    id: 6,
    name: "Hyundai Venue",
    brand: "Hyundai",
    price: 1050000,
    year: 2022,
    mileage: "18 km/l",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "998 cc",
    rating: 4.3,
    image: "images/cars/hyundai-venue.jpg",
    description: "A compact urban SUV with connected-car features, peppy turbo engine options, and easy city maneuverability."
  },
  {
    id: 7,
    name: "Hyundai i20",
    brand: "Hyundai",
    price: 950000,
    year: 2021,
    mileage: "19 km/l",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1197 cc",
    rating: 4.1,
    image: "images/cars/hyundai-i20.jpg",
    description: "A premium hatchback with a stylish design, well-finished interiors, and multiple engine and transmission choices."
  },
  {
    id: 8,
    name: "Hyundai Verna",
    brand: "Hyundai",
    price: 1450000,
    year: 2023,
    mileage: "18 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1482 cc",
    rating: 4.4,
    image: "images/cars/hyundai-verna.jpg",
    description: "A feature-loaded mid-size sedan with a strong turbo-petrol engine and a comfortable, premium cabin."
  },
  {
    id: 9,
    name: "Toyota Fortuner",
    brand: "Toyota",
    price: 3900000,
    year: 2022,
    mileage: "11 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "2755 cc",
    rating: 4.6,
    image: "images/cars/toyota-fortuner.jpg",
    description: "A full-size ladder-frame SUV renowned for its reliability, off-road capability, and strong resale value."
  },
  {
    id: 10,
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    price: 2800000,
    year: 2021,
    mileage: "13 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "2393 cc",
    rating: 4.7,
    image: "images/cars/toyota-innova-crysta.jpg",
    description: "A benchmark people-mover offering excellent comfort, durability, and long-distance touring abilities."
  },
  {
    id: 11,
    name: "Toyota Glanza",
    brand: "Toyota",
    price: 900000,
    year: 2022,
    mileage: "22 km/l",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1197 cc",
    rating: 4.0,
    image: "images/cars/toyota-glanza.jpg",
    description: "A premium hatchback with efficient petrol engines, comfortable seating, and a smooth city driving experience."
  },
  {
    id: 12,
    name: "Toyota Urban Cruiser Hyryder",
    brand: "Toyota",
    price: 1900000,
    year: 2023,
    mileage: "27 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1490 cc",
    rating: 4.5,
    image: "images/cars/toyota-urban-cruiser-hyryder.jpg",
    description: "A strong-hybrid mid-size SUV delivering excellent fuel efficiency and smooth, quiet electric-assisted driving."
  },
  {
    id: 13,
    name: "Honda City",
    brand: "Honda",
    price: 1500000,
    year: 2023,
    mileage: "18 km/l",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1498 cc",
    rating: 4.6,
    image: "images/cars/honda-city.jpg",
    description: "A legendary mid-size sedan known for its refined engine, spacious cabin, and strong reliability."
  },
  {
    id: 14,
    name: "Honda Amaze",
    brand: "Honda",
    price: 900000,
    year: 2021,
    mileage: "18 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1199 cc",
    rating: 4.0,
    image: "images/cars/honda-amaze.jpg",
    description: "A compact sedan offering a comfortable ride, practical boot space, and smooth automatic gearbox options."
  },
  {
    id: 15,
    name: "Honda WR-V",
    brand: "Honda",
    price: 1150000,
    year: 2020,
    mileage: "17 km/l",
    fuel: "Diesel",
    transmission: "Manual",
    engine: "1498 cc",
    rating: 3.9,
    image: "images/cars/honda-wrv.jpg",
    description: "A crossover-styled hatchback with good ground clearance and a fuel-efficient diesel engine."
  },
  {
    id: 16,
    name: "Mahindra XUV700",
    brand: "Mahindra",
    price: 2300000,
    year: 2023,
    mileage: "15 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "2184 cc",
    rating: 4.8,
    image: "images/cars/mahindra-xuv700.jpg",
    description: "A tech-loaded SUV with powerful engines, ADAS features, and an impressive highway cruising ability."
  },
  {
    id: 17,
    name: "Mahindra Scorpio N",
    brand: "Mahindra",
    price: 2100000,
    year: 2022,
    mileage: "14 km/l",
    fuel: "Diesel",
    transmission: "Manual",
    engine: "2184 cc",
    rating: 4.4,
    image: "images/cars/mahindra-scorpio-n.jpg",
    description: "A rugged SUV combining traditional Scorpio toughness with a more premium and comfortable interior."
  },
  {
    id: 18,
    name: "Mahindra Thar",
    brand: "Mahindra",
    price: 1700000,
    year: 2021,
    mileage: "13 km/l",
    fuel: "Diesel",
    transmission: "Manual",
    engine: "2184 cc",
    rating: 4.3,
    image: "images/cars/mahindra-thar.jpg",
    description: "An iconic off-roader with modern comforts, removable roof options, and excellent off-road capability."
  },
  {
    id: 19,
    name: "Mahindra Bolero Neo",
    brand: "Mahindra",
    price: 1100000,
    year: 2020,
    mileage: "17 km/l",
    fuel: "Diesel",
    transmission: "Manual",
    engine: "1493 cc",
    rating: 3.8,
    image: "images/cars/mahindra-bolero-neo.jpg",
    description: "A tough, ladder-frame SUV designed for rough roads, offering durable mechanicals and practical seating."
  },
  {
    id: 20,
    name: "Kia Seltos",
    brand: "Kia",
    price: 1650000,
    year: 2023,
    mileage: "17 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1482 cc",
    rating: 4.5,
    image: "images/cars/kia-seltos.jpg",
    description: "A stylish mid-size SUV with a premium interior, multiple powertrain choices, and strong feature list."
  },
  {
    id: 21,
    name: "Kia Sonet",
    brand: "Kia",
    price: 1150000,
    year: 2022,
    mileage: "18 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "1493 cc",
    rating: 4.2,
    image: "images/cars/kia-sonet.jpg",
    description: "A compact SUV packed with features, offering multiple engine options and a youthful, sporty design."
  },
  {
    id: 22,
    name: "Kia Carens",
    brand: "Kia",
    price: 1700000,
    year: 2022,
    mileage: "16 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1497 cc",
    rating: 4.1,
    image: "images/cars/kia-carens.jpg",
    description: "A three-row MPV with flexible seating, a long feature list, and a family-friendly cabin."
  },
  {
    id: 23,
    name: "BMW X1",
    brand: "BMW",
    price: 4800000,
    year: 2023,
    mileage: "14 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1998 cc",
    rating: 4.6,
    image: "images/cars/bmw-x1.jpg",
    description: "A premium compact luxury SUV offering a refined drive, high-quality interiors, and strong brand appeal."
  },
  {
    id: 24,
    name: "BMW X3",
    brand: "BMW",
    price: 6500000,
    year: 2022,
    mileage: "12 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "1995 cc",
    rating: 4.5,
    image: "images/cars/bmw-x3.jpg",
    description: "A mid-size luxury SUV balancing sporty dynamics with comfortable long-distance touring ability."
  },
  {
    id: 25,
    name: "BMW 3 Series",
    brand: "BMW",
    price: 5200000,
    year: 2021,
    mileage: "15 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1998 cc",
    rating: 4.7,
    image: "images/cars/bmw-3-series.jpg",
    description: "A sport sedan icon delivering engaging handling, refined powertrains, and a driver-focused cockpit."
  },
  {
    id: 26,
    name: "BMW X5",
    brand: "BMW",
    price: 8500000,
    year: 2020,
    mileage: "11 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "2993 cc",
    rating: 4.6,
    image: "images/cars/bmw-x5.jpg",
    description: "A large luxury SUV with powerful engines, plush interiors, and strong road presence."
  },
  {
    id: 27,
    name: "Mercedes GLA",
    brand: "Mercedes",
    price: 4600000,
    year: 2022,
    mileage: "15 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1332 cc",
    rating: 4.4,
    image: "images/cars/mercedes-gla.jpg",
    description: "A compact luxury SUV offering the Mercedes badge, modern interiors, and comfortable city manners."
  },
  {
    id: 28,
    name: "Mercedes GLC",
    brand: "Mercedes",
    price: 7200000,
    year: 2023,
    mileage: "13 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "1950 cc",
    rating: 4.6,
    image: "images/cars/mercedes-glc.jpg",
    description: "A mid-size luxury SUV that combines a plush cabin, refined engines, and a relaxed driving experience."
  },
  {
    id: 29,
    name: "Mercedes C-Class",
    brand: "Mercedes",
    price: 6100000,
    year: 2022,
    mileage: "16 km/l",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "1993 cc",
    rating: 4.7,
    image: "images/cars/mercedes-c-class.jpg",
    description: "A luxury sedan with a beautifully finished interior, advanced tech, and a smooth, efficient powertrain."
  },
  {
    id: 30,
    name: "Mercedes E-Class",
    brand: "Mercedes",
    price: 8200000,
    year: 2021,
    mileage: "14 km/l",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1991 cc",
    rating: 4.8,
    image: "images/cars/mercedes-e-class.jpg",
    description: "An executive luxury sedan renowned for its comfort, rear-seat space, and sophisticated driving experience."
  }
];

window.carsData = carsData;
